# Generated by Django 3.1.2 on 2021-02-27 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegname', models.CharField(max_length=50, verbose_name='Тэг')),
            ],
        ),
        migrations.CreateModel(
            name='MainArticleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_article', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('teg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.teg')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Tegs',
            field=models.ManyToManyField(blank=True, related_name='articles', through='articles.MainArticleChoice', to='articles.Teg'),
        ),
    ]
