# Generated by Django 3.1.2 on 2021-02-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teg',
            old_name='tegname',
            new_name='teg',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Tegs',
        ),
        migrations.AddField(
            model_name='teg',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='articles', through='articles.MainArticleChoice', to='articles.Article'),
        ),
    ]
